"""add total_exposure to reconciliation_runs

Revision ID: 4184c40b1b17
Revises: b9834b82204c
Create Date: 2026-09-11 15:47:06.777804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4184c40b1b17'
down_revision: Union[str, Sequence[str], None] = 'b9834b82204c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_runs', sa.Column('total_exposure', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_runs', 'total_exposure')
    # ### end Alembic commands ###
