"""m4 initial schema

Revision ID: b9834b82204c
Revises: 
Create Date: 2026-09-11 14:41:38.587228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9834b82204c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_sha256'), 'uploaded_files', ['sha256'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('error_row_count', sa.Integer(), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unmapped_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_uploaded_file_id'), 'ingestion_runs', ['uploaded_file_id'], unique=False)
    op.create_table('reconciliation_runs',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('tolerances', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_runs_ingestion_run_id'), 'reconciliation_runs', ['ingestion_run_id'], unique=False)
    op.create_table('staging_records',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'row_number')
    )
    op.create_index(op.f('ix_staging_records_ingestion_run_id'), 'staging_records', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_staging_records_is_valid'), 'staging_records', ['is_valid'], unique=False)
    op.create_table('vendors',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('vendor_code', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'normalized_name')
    )
    op.create_index(op.f('ix_vendors_ingestion_run_id'), 'vendors', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_vendors_normalized_name'), 'vendors', ['normalized_name'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=128), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'po_number')
    )
    op.create_index(op.f('ix_purchase_orders_ingestion_run_id'), 'purchase_orders', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_table('grns',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('grn_ref', sa.String(length=128), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('grn_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'grn_ref')
    )
    op.create_index(op.f('ix_grns_grn_ref'), 'grns', ['grn_ref'], unique=False)
    op.create_index(op.f('ix_grns_ingestion_run_id'), 'grns', ['ingestion_run_id'], unique=False)
    op.create_table('invoices',
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'invoice_number')
    )
    op.create_index(op.f('ix_invoices_ingestion_run_id'), 'invoices', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=512), nullable=False),
    sa.Column('item_code', sa.String(length=128), nullable=True),
    sa.Column('normalized_item', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('staging_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staging_record_id'], ['staging_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_normalized_item'), 'purchase_order_lines', ['normalized_item'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('grn_lines',
    sa.Column('grn_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=True),
    sa.Column('item', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('staging_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staging_record_id'], ['staging_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_lines_grn_id'), 'grn_lines', ['grn_id'], unique=False)
    op.create_index(op.f('ix_grn_lines_purchase_order_line_id'), 'grn_lines', ['purchase_order_line_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=True),
    sa.Column('item', sa.String(length=512), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('staging_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staging_record_id'], ['staging_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_purchase_order_line_id'), 'invoice_lines', ['purchase_order_line_id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('reconciliation_run_id', sa.UUID(), nullable=False),
    sa.Column('staging_record_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=True),
    sa.Column('grn_line_id', sa.UUID(), nullable=True),
    sa.Column('invoice_line_id', sa.UUID(), nullable=True),
    sa.Column('system_status', sa.String(length=32), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grn_line_id'], ['grn_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staging_record_id'], ['staging_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_results_current_status'), 'reconciliation_results', ['current_status'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_reconciliation_run_id'), 'reconciliation_results', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_staging_record_id'), 'reconciliation_results', ['staging_record_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_results_system_status'), 'reconciliation_results', ['system_status'], unique=False)
    op.create_table('decision_log',
    sa.Column('reconciliation_result_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_result_id'], ['reconciliation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_log_action'), 'decision_log', ['action'], unique=False)
    op.create_index(op.f('ix_decision_log_actor'), 'decision_log', ['actor'], unique=False)
    op.create_index(op.f('ix_decision_log_decided_at'), 'decision_log', ['decided_at'], unique=False)
    op.create_index(op.f('ix_decision_log_is_system'), 'decision_log', ['is_system'], unique=False)
    op.create_index(op.f('ix_decision_log_reconciliation_result_id'), 'decision_log', ['reconciliation_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_log_reconciliation_result_id'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_is_system'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_decided_at'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_actor'), table_name='decision_log')
    op.drop_index(op.f('ix_decision_log_action'), table_name='decision_log')
    op.drop_table('decision_log')
    op.drop_index(op.f('ix_reconciliation_results_system_status'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_staging_record_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_reconciliation_run_id'), table_name='reconciliation_results')
    op.drop_index(op.f('ix_reconciliation_results_current_status'), table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index(op.f('ix_invoice_lines_purchase_order_line_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_grn_lines_purchase_order_line_id'), table_name='grn_lines')
    op.drop_index(op.f('ix_grn_lines_grn_id'), table_name='grn_lines')
    op.drop_table('grn_lines')
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_normalized_item'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_ingestion_run_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_grns_ingestion_run_id'), table_name='grns')
    op.drop_index(op.f('ix_grns_grn_ref'), table_name='grns')
    op.drop_table('grns')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_ingestion_run_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_vendors_normalized_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_ingestion_run_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_staging_records_is_valid'), table_name='staging_records')
    op.drop_index(op.f('ix_staging_records_ingestion_run_id'), table_name='staging_records')
    op.drop_table('staging_records')
    op.drop_index(op.f('ix_reconciliation_runs_ingestion_run_id'), table_name='reconciliation_runs')
    op.drop_table('reconciliation_runs')
    op.drop_index(op.f('ix_ingestion_runs_uploaded_file_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_uploaded_files_sha256'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
